import {
  GraduationCap,
  BookOpen,
  Award,
  PenLine,
  Newspaper,
  FlaskConical,
  Landmark,
  Palette,
  Cpu,
  BarChart2,
  MonitorSmartphone,
  PieChart,
  Settings2,
  Coins,
  LibraryBig,
  Code2,
  FileText,
  ClipboardList,
  ScanSearch,
  Pencil,
  Database,
  Globe,
  Star,
  ActivitySquare,
  BadgeCheck,
  Briefcase,
  Crown,
} from "lucide-react";

export const homeFeatures = [
  { title: "Dashboard", description: "Overview of your activity", href: "#" },
  { title: "Analytics", description: "Track your performance", href: "#" },
  { title: "Settings", description: "Configure your preferences", href: "#" },
  { title: "Integrations", description: "Connect with other tools", href: "#" },
  { title: "Storage", description: "Manage your files", href: "#" },
  { title: "Support", description: "Get help when needed", href: "#" },
];

export const servicesDomains = [
  {
    label: "Global Doctoral Programs",
    icon: <GraduationCap className="h-4 w-4 shrink-0" />,
    title: "Global Doctoral Programs",
    subtitle: "World-class doctoral pathways across disciplines",
    sectionLabel: "Program type",
    type: "grid",
    items: [
      {
        icon: <BadgeCheck className="h-4 w-4" />,
        name: "PhD",
        tag: "Doctor of Philosophy",
        href: "/courses/phd",
      },
      {
        icon: <Briefcase className="h-4 w-4" />,
        name: "DBA",
        tag: "Doctor of Business Administration",
        href: "/courses/dba",
      },
      {
        icon: <Crown className="h-4 w-4" />,
        name: "Honorary Doctorate",
        tag: "Distinguished achievement",
        href: "/courses/honorary-doctorate",
      },
    ],
  },
  {
    label: "UG Programs",
    icon: <BookOpen className="h-4 w-4 shrink-0" />,
    title: "UG Programs",
    subtitle: "Build a strong academic foundation",
    sectionLabel: "Undergraduate degrees",
    type: "grid",
    items: [
      {
        icon: <FlaskConical className="h-4 w-4" />,
        name: "B.Sc",
        tag: "Bachelor of Science",
        href: "/courses/bsc",
      },
      {
        icon: <Coins className="h-4 w-4" />,
        name: "B.Com",
        tag: "Bachelor of Commerce",
        href: "/courses/bcom",
      },
      {
        icon: <Palette className="h-4 w-4" />,
        name: "B.A",
        tag: "Bachelor of Arts",
        href: "/courses/ba",
      },
      {
        icon: <Cpu className="h-4 w-4" />,
        name: "B.Tech",
        tag: "Bachelor of Technology",
        href: "/courses/btech",
      },
      {
        icon: <BarChart2 className="h-4 w-4" />,
        name: "BBA",
        tag: "Bachelor of Business Administration",
        href: "/courses/bba",
      },
      {
        icon: <MonitorSmartphone className="h-4 w-4" />,
        name: "BCA",
        tag: "Bachelor of Computer Applications",
        href: "/courses/bca",
      },
    ],
  },
  {
    label: "PG Programs",
    icon: <Award className="h-4 w-4 shrink-0" />,
    title: "PG Programs",
    subtitle: "Advanced degrees for career acceleration",
    sectionLabel: "Postgraduate degrees",
    type: "grid",
    items: [
      {
        icon: <PieChart className="h-4 w-4" />,
        name: "MBA",
        tag: "Master of Business Administration",
        href: "/courses/mba",
      },
      {
        icon: <Settings2 className="h-4 w-4" />,
        name: "M.Tech",
        tag: "Master of Technology",
        href: "/courses/mtech",
      },
      {
        icon: <Landmark className="h-4 w-4" />,
        name: "M.Com",
        tag: "Master of Commerce",
        href: "/courses/mcom",
      },
      {
        icon: <LibraryBig className="h-4 w-4" />,
        name: "M.A",
        tag: "Master of Arts",
        href: "/courses/ma",
      },
      {
        icon: <Code2 className="h-4 w-4" />,
        name: "MCA",
        tag: "Master of Computer Applications",
        href: "/courses/mca",
      },
    ],
  },
  {
    label: "Writing Services",
    icon: <PenLine className="h-4 w-4 shrink-0" />,
    title: "Writing Services",
    subtitle: "Professional academic writing support",
    sectionLabel: "Research & academic writing",
    type: "list",
    items: [
      {
        icon: <FileText className="h-4 w-4" />,
        name: "Thesis Writing",
        href: "/courses/thesis-writing",
      },
      {
        icon: <ClipboardList className="h-4 w-4" />,
        name: "Dissertation Writing",
        href: "/courses/dissertation-writing",
      },
      {
        icon: <ScanSearch className="h-4 w-4" />,
        name: "Research & Review Papers",
        href: "/courses/research-review-papers",
      },
      {
        icon: <Pencil className="h-4 w-4" />,
        name: "Other Academic Writing",
        href: "/courses/academic-writing",
      },
    ],
  },
  {
    label: "Publications",
    icon: <Newspaper className="h-4 w-4 shrink-0" />,
    title: "Publications",
    subtitle: "Get your research into top-indexed journals",
    sectionLabel: "Publication services",
    type: "list",
    items: [
      {
        icon: <Database className="h-4 w-4" />,
        name: "Scopus Publications",
        href: "/courses/scopus",
      },
      {
        icon: <Globe className="h-4 w-4" />,
        name: "Web of Science",
        href: "/courses/web-of-science",
      },
      {
        icon: <Star className="h-4 w-4" />,
        name: "ABDC Publications",
        href: "/courses/abdc",
      },
      {
        icon: <ActivitySquare className="h-4 w-4" />,
        name: "PUBMED / EMBASE",
        href: "/courses/pubmed-embase",
      },
    ],
  },
];